import { formatKey, formatPairs, formatTime, formatValue, plural, tableLabel } from '../format.js';
import type { Change, Marker, Recording } from '../types.js';
import { summarize } from './summary.js';

const MAX_VALUE_LENGTH = 80;

/** Escapes text for a Markdown table cell. */
function cell(text: string): string {
  return text.replace(/\\/g, '\\\\').replace(/\|/g, '\\|').replace(/</g, '&lt;').replace(/`/g, '\\`');
}

function details(change: Change): string {
  const keyCols = new Set(Object.keys(change.rowKey ?? {}));
  switch (change.op) {
    case 'INSERT':
      return cell(formatPairs(change.newValues, keyCols, MAX_VALUE_LENGTH));
    case 'UPDATE':
      return Object.keys(change.newValues ?? {})
        .map((col) => `${cell(col)}: ${cell(formatValue(change.oldValues?.[col], MAX_VALUE_LENGTH))} → **${cell(formatValue(change.newValues?.[col], MAX_VALUE_LENGTH))}**`)
        .join('<br>');
    case 'DELETE':
      return cell(formatPairs(change.oldValues, keyCols, MAX_VALUE_LENGTH));
    case 'TRUNCATE':
      return 'every row removed';
  }
}

export interface ExportOptions {
  masked: boolean;
  hidden?: number;
}

/** A Markdown report for bug tickets and pull requests. */
const MARKER_LABEL = { pause: '‖ **Paused**', resume: '● **Resumed**', flag: '⚑ **Flagged**' } as const;

export function toMarkdown(rec: Recording, { masked, hidden = 0 }: ExportOptions): string {
  const s = summarize(rec);
  const out: string[] = [
    `# Propmaster recording: ${rec.name}`,
    '',
    '| | |',
    '| --- | --- |',
    `| Session | #${rec.id} (${rec.mode} mode) |`,
    `| Database | ${cell(rec.database)} |`,
    `| Recorded | ${s.recorded} |`,
    `| Changes | ${s.text}${hidden ? `, ${plural(hidden, 'change')} hidden by filters` : ''} |`,
    '',
  ];

  for (const note of rec.notes) out.push(`> **Note:** ${cell(note)}`, '');

  for (const step of rec.steps) {
    const markers = step.markers ?? [];
    if (step.seq === 0 && step.changes.length === 0 && markers.length === 0) continue;
    out.push(`## Step ${step.seq} · ${cell(step.name)} (${plural(step.changes.length, 'change')})`, '');
    if (markers.length) {
      out.push(...markers.map((m) => `- ${MARKER_LABEL[m.kind]} at ${formatTime(m.at)}${m.note ? `: ${cell(m.note)}` : ''}`), '');
    }
    if (step.changes.length === 0) {
      out.push('_No database changes._', '');
      continue;
    }
    out.push('| Op | Table | Row | Details |', '| --- | --- | --- | --- |');
    for (const c of step.changes) {
      out.push(`| ${c.op} | ${cell(tableLabel(c))} | ${cell(formatKey(c) ?? '(no primary key)')} | ${details(c)} |`);
    }
    out.push('');
  }

  out.push(`_Generated by Propmaster. ${masked ? 'Sensitive values are masked.' : '**Values are not masked.**'}_`, '');
  return out.join('\n');
}
